##
# ci-renovate.yaml
# Automates dependency updates using Renovate.
##

name: Renovate
on:
  workflow_call:
    inputs:
      logLevel:
        description: "Override default log level"
        required: false
        default: "info"
        type: string
      overrideSchedule:
        description: "Override all schedules"
        required: false
        default: "false"
        type: string
concurrency: renovate

permissions:
  contents: read
  issues: write
  pull-requests: write
  actions: read
  checks: write
  deployments: write
  statuses: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    # Timeout-minutes to prevent hanging
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Renovate JSON
        run: jq type .github/renovate.json || exit 1

      - name: Get token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.RENOVATE_APP_ID }}
          private-key: ${{ secrets.RENOVATE_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v41.0.13
        env:
          # Repository taken from variable to keep configuration file generic
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          # Onboarding not needed for self hosted
          RENOVATE_ONBOARDING: "false"
          # Username for GitHub authentication (should match GitHub Application name + [bot])
          RENOVATE_USERNAME: "sosadtsia-renovatebot[bot]"
          # Git commit author used, must match GitHub App
          RENOVATE_GIT_AUTHOR: "sosadtsia-renovatebot <1149912+sosadtsia-renovatebot[bot]@users.noreply.github.com>"
          # Use GitHub API to create commits (this allows for signed commits from GitHub App)
          RENOVATE_PLATFORM_COMMIT: "true"
          # Override schedule if set
          RENOVATE_FORCE: ${{ github.event.inputs.overrideSchedule == 'true' && '{''schedule'':null}' || '' }}
          LOG_LEVEL: ${{ inputs.logLevel || 'info' }}
        with:
          configurationFile: .github/renovate.json
          token: '${{ steps.app-token.outputs.token }}'