##
# linter.yaml
# Runs static code analysis agaist changes in the feature branch.
# See `https://github.com/github/super-linter#supported-linters` for more details.
##
---
name: 'Lint/static code analysis'
on:
  workflow_dispatch: {}

jobs:
  linter:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write

    steps:
      - name: Checksout code
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - run: cat .github/super-linter.env >> "$GITHUB_ENV"
      - name: Lint Code Base
        uses: super-linter/super-linter@v8.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: true
          IGNORE_GITIGNORED_FILES: true
          IGNORE_GENERATED_FILES: true
