##
# node-code-promotion.yaml
# Code promotion into the target environment.
##
---
name: Code promotion

on:
  workflow_call:
    inputs:
      target-branch:
        type: string
        description: Target branch in `<REPOSITORY>` for code promotion
        required: true

jobs:
  promotion:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: read

    steps:
      - run: echo '🔎 The job was automatically triggered by a ${{ github.event_name }} event.'

      - run: echo 'The name the branch is `${{ github.ref_name }}` repository name is `${{ github.repository }}`.'

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '22.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: ''

      - name: Install package
        run: echo 'npm install -g <PACKAGE>'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test package
        id: test
        run: echo '<PACKAGE> help'

      - name: Code promotion to branch "${{ inputs.target-branch }}"
        if: steps.test.outputs.exit_code == 0
        run: echo '<PACKAGE> promote ${{ github.event.repository.name }} ${{ inputs.target-branch }}'

      - name: Check status of the job
        run: echo "🍏 This job's status is ${{ job.status }}."
